services:
	- type: web
		name: rollwala-placement-portal
		env: node
		plan: free
		buildCommand: rm -rf node_modules package-lock.json && npm install
		startCommand: node server.js
		envVars:
			- key: MONGODB_URI
				value: mongodb+srv://hemjshah052:hem0502@cluster0.vd6tt.mongodb.net/placement?retryWrites=true&w=majority
		autoDeploy: true
		rootDir: backend
